name: github_user_project
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  logger: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  freezed: ^1.1.1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
  generate: true
